### ISSUE TITLE
Back navigation

### ISSUE THREAD

**Issue by ElBurritoPodrido** [openwhyd/openwhyd-electron#8]
Hi all,

Not sure if this is an issue or a feature request. I tried the app for mac yesterday for the first time - love it! I'm running Sierra 10.12.5
When I browse the site through the app, I can not "go back".
For example, if I do the following:

- Go to a profile
- Browse playlists availables
- Open a playlists and browse it

I can not go back directly to browsing the available playlists. I need to go back to the profile, then open the playlists again.
It is a small enhancement, but it would make for a smoother navigation through the app, and it would be easier to explore the others' playlists.

**Comment by adrienjoly** [comment]
Thank you for posting this feature request here, @ElBurritoPodrido ! :-)

Do you have any idea / proposition on how to do this, by any chance?

It was also reported that the Ctrl-F / Cmd-F keyboard shortcut for search did not work from the electron app. Maybe we could find a way to solve those two problems at once?

**Comment by ElBurritoPodrido** [comment]
No I'm sorry, I'm clueless :-( I know more of Python and backend stuff. I am not super familiar with how to build an app like this. I'll take a look at the code though, I am curious now!

**Comment by ElBurritoPodrido** [comment]
Actually, for Ctrl F I saw this thread https://github.com/electron/electron/issues/2037 pointing toward
https://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options

And for back navigation, this document describes an Electron API for navigation https://github.com/electron/electron/blob/master/docs/api/web-contents.md

> contents.goBack()
> 
> Makes the browser go back a web page.

Does this help?

**Comment by adrienjoly** [comment]
Thanks for sharing your findings, Henri!

Both of your solution use Electron's API for controlling the "browser".

Concerning the "back" navigation:
- I'm wondering if `window.history.back();` would also work (this is a standard *web browser* function) instead of Electron's `webContents.back()`
- We'll have to discuss about how to display an actual "back" button on the UI, as Electron does not have a navigation bar (as opposed to typical web browsers). Maybe we could consider integrating something like [electron-navigation](https://www.npmjs.com/package/electron-navigation), if we find a way to disable tabs. (or at least make sure that they would not cause the "skipping tracks" problems that motivated this openwhyd-electron project in the first place!)

Concerning in-page search:
- Similarly to the navigation issue, Electron does provide an API to find text occurrences in the page, but it does not provide a UI for it. => We'll also have to discuss a simple way to integrate the in-page search feature, together with its UI.
- [electron-in-page-search](https://github.com/rhysd/electron-in-page-search) could be a simple and integrated solution to that problem. What do you think?

**Comment by adrienjoly** [comment]
Note: `window.history.back()` does work.

**Comment by adrienjoly** [comment]
Done in v1.0.0-rc.1 => closing
